api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
    formats:
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        html:     ['text/html']
    enable_swagger_ui: true
